# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# image: registry.gitlab.com/pages/hugo:latest
# image: monachus/hugo

# variables:
#   GIT_SUBMODULE_STRATEGY: recursive

# test:
#   script:
#     - hugo
#   except:
#     - source

# pages:
#   script:
#     - hugo
#   artifacts:
#     paths:
#       - public
#   only:
#     - source

image: "node:alpine"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  before_script:
    - "which curl || ( apk update && apk add curl)"
    - "which gem || (apk add ruby)"
    - bash install_hugo.sh
    - npm install
    - gem install asciidoctor
  script:
    - gulp prod
  only:
    - source
  artifacts:
    paths:
      - public
    expire_in: 2 hours
