# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# image: registry.gitlab.com/pages/hugo:latest
image: registry.gitlab.com/yashhere/docker-hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - source

pages:
  before_script:
    - apt update
    - apt install -y imagemagick jq make
  script:
    - make
#    - go run scripts/goodreads.go scripts/goodReadsApi.go
#    - go run scripts/letterboxd.go
#    - bash scripts/get_data_from_sheets.sh
#    - hugo --gc --minify
#    - find ./public -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) -print0 | xargs -0 -P16 -n2 mogrify -compress JPEG -strip -quality 40
#    - gzip -k -6 -r $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - source