# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# image: registry.gitlab.com/pages/hugo:latest
image: registry.gitlab.com/yashhere/docker-hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - source

pages:
  script:
    - make
    -
    - gzip -k -6 -r $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - source