# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# image: registry.gitlab.com/pages/hugo:latest
image: registry.gitlab.com/yashhere/docker-hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - source

pages:
  script:
    - make
    - git config credential.helper envvar
    - git config user.name  $GITCREDENTIALUSERNAME
    - git config user.email $GITCREDENTIALEMAIL
    - git add data/library.json
    - git commit -m "Updating bookmarks [skip ci]" || echo "No changes to bookmarks"
    - git push
    - gzip -k -6 -r $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - source