Paginate: 7
baseURL: https://yashagarwal.in
canonifyurls: true
MetaDataFormat: "yaml"
archetypeDir: "archetypes"
config: "config.toml"
enableGitInfo: false
copyright: Creative Commons Attribution-ShareAlike 4.0 International License
defaultContentLanguage: en
disqusShortname: yashhere
googleAnalytics: "UA-75475356-3"
enableEmoji: true
enableRobotsTXT: true
languages:
  en:
    lang: en
    languageName: English
    weight: 1
menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 10
  - identifier: posts
    name: Posts
    url: /posts
  - name: whoami
    url: /whoami
  - identifier: Readings
    title: Readings
    name: Readings
    url: /readings
params:
  assets:
    customCSS:
    - css/custom.css
    - css/syntax.css
    - css/chroma-styles.css
    - css/footnotes.css
    customJS:
    - js/jquery.js
    - js/redirection.js
    - js/footnoteTooltip.js
    favicon: favicon.ico
    gopher: ''
  copyright:
    holder: Yash Agarwal
    startYear: '2015'
    suffix: ' - Creative Commons Attribution-ShareAlike 4.0 International License'
  info:
    description: The directory of my thoughts
    title404: Nothing's here!
  seo:
    titleSeparator: •
  settings:
    dateFormat: Jan 02, 2006
    hideSocialMenu: false
    listDateFormat: Jan 02, 2006
    showReadingTime: true
  social:
    config:
      platforms:
      - github
      - facebook
      - twitter
      - instagram
      - codepen
      - linkedin
    facebook: profile.php?id=100001324105675
    github: yashhere
    instagram: yum_yash
    linkedin: theyashagarwal
    twitter: yash__here
permalinks:
  page: /:title/
  posts: /posts/:year/:month/:slug/
  readings: /readings/:year/:month/:slug
preserveTaxonomyNames: true
pygmentsCodeFencesGuessSyntax: true
pygmentsuseclasses: true
pygmentsOptions:
  linenostart: 1
  linenos: table
taxonomies:
  author: authors
  category: categories
  tag: tags
theme: minimo
title: /dev/yash/notes

blackfriday:
  hrefTargetBlank: true
  taskLists: true
  fractions: true
  smartDashes: true

related:
  threshold: 80
  includeNewer: false
  toLower: false
  indices:
    - name: "keywords"
    - weight: 150
  indices:
    - name : "author"
    - toLower: true
    - weight: 30
  indices:
    - name : "tags"
    - weight: 100
  indices:
    - name : "date"
    - weight: 10
    - pattern: "2006"
