languageCode = "en-us"
title = "/dev/yash/notes"
baseurl = "https://yashagarwal.me"
theme = "liquorice"
canonifyurls = true
pygmentsStyle = "native"
enableEmoji=true

[Params]
	Author = "Yash Agarwal"
	copyright = "© Yash Agarwal 2017 - Creative Commons Attribution-ShareAlike 4.0 International License"
	gaCode = "UA-75475356-2"
	disqusShortname = "theyashagarwal"

[indexes]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:year/:month/:slug/"
  page = "/:title/"
  
[[menu.main]]
  name = "Posts"
  url = "/posts"
[[menu.main]]
  name = "About"
  url = "/about"
  weight = 100
