BaseURL: "https://tufte.yashagarwal.in/"
Title: /dev/yash/notes

contentdir: content
layoutdir: layouts
publishdir: public
cleandestinationdir: true

pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: false
pygmentsCodeFencesGuessSyntax: true
pygmentsOptions:
  linenostart: 1
  linenos: table

paginate: 5
enableEmoji: true
enableRobotsTXT: true
languageCode: en-us
enableGitInfo: false
disableFastRender: true
disableHugoGeneratorInject: true
disqusShortname: yashhere
timeout: 60000

Author:
  name: Yash Agarwal
  email: yashagarwaljpr+blog@gmail.com
  bio: ""
  photo:
    url: author/yash.jpg
    width: 400
    height: 400

Permalinks:
  posts: ":sections/:year/:month/:slug/"

Taxonomies:
  category: categories
  tag: tags
  series: series

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - ATOM
    - JF2Feed
    - HEADERS
    - REDIRECTS
  section:
    - HTML
    - RSS
    - ATOM
    - JF2Feed
  taxonomy:
    - HTML
    - RSS
    - ATOM
    - JF2Feed
  taxonomyTerm:
    - HTML
  page:
    - HTML
    - JF2Post

caches:
  getjson:
    dir: ":cacheDir/:project"
    maxAge: 10s
  getcsv:
    dir: ":cacheDir/:project"
    maxAge: 10s

# remove .{ext} from text/netlify
mediaTypes:
  text/netlify:
    suffixes:
      - ''
    delimiter: ''

outputFormats:
  # add output format for netlify _redirects
  REDIRECTS:
    mediatype: text/netlify
    baseName: _redirects
    isPlainText: true
    notAlternative: true
  # add output format for netlify _headers
  HEADERS:
    mediatype: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true

Params:
  image:
    quality: 85
    bgColor: '#fff'
    landscapePhotoWidths:
      - 900
      - 800
      - 500
    portraitPhotoWidths:
      - 800
      - 500
    lqipWidth: 20x
    smallLimit: '320'
  settings:
    showReadingTime: true
  copyright:
    startyear: 2016
  mainSections:
    - posts
    - about
    - search
  tagline: "The directory of my thoughts"
  favicons: true
  feedSections:
    - posts

  source:
    url: "https://github.com/yashhere/tufte.yashagarwal.in"
    md_dir: content
    branch: source

  #  indieweb:
  #    domain: "https://tufte.yashagarwal.in/"
  #    webring: "\U00003297\U0000fe0f\U0001f34b\U0001f468\U0000200d\U0001f468\U0000200d\U0001f467\U0000200d\U0001f467"
  #    webmention:
  #      endpoint: "https://webmention.io/"
  #      account: "https://tufte.yashagarwal.in"

  social:
    email:
      - address: yashagarwaljpr+blog@gmail.com
    github:
      - address: yashhere
        relme: true
    gitlab:
      - address: yashhere
    instagram:
      - address: yum_yash
    linkedin:
      - address: theyashagarwal
    twitter:
      - address: yash__here

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: true
    enableDNT: true
    simple: false
  # vimeo:
  #   disable: true
  #   simple: false
  # youtube:
  #   disable: true
  #   privacyEnhanced: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 2

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false

minify:
  tdewolff:
    html:
      keepWhitespace: false

module:
  imports:
  - path: github.com/yashhere/hugo-theme-tufte

