BaseURL: "https://yashagarwal.in/"
Title: /dev/yash/notes
theme: tufte

contentdir: content
layoutdir: layouts
publishdir: public
cleandestinationdir: true

pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: false
pygmentsCodeFencesGuessSyntax: true
pygmentsOptions:
  linenostart: 1
  linenos: table

enableEmoji: true
enableRobotsTXT: true
LanguageCode: en-us
disableFastRender: true
disqusShortname: yashhere

Author:
  name: Yash Agarwal
  email: yashagarwaljpr@gmail.com
  bio: ""
  photo:
    url: author/yash.jpg
    width: 400
    height: 400

Permalinks:
  posts: ":sections/:year/:month/:slug/"
  updates: ":sections/:year/:month/:slug/"
  books: ":sections/:year/:month/:slug/"


Taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - ATOM
    - JF2Feed
  section:
    - HTML
    - RSS
    - ATOM
    - JF2Feed
  taxonomy:
    - HTML
    - RSS
    - ATOM
    - JF2Feed
  taxonomyTerm:
    - HTML
  page:
    - HTML
    - JF2Post

caches:
  getjson:
    dir: ":cacheDir/:project"
    maxAge: 1m
  getcsv:
    dir: ":cacheDir/:project"
    maxAge: 1m

Params:
  settings:
    showReadingTime: true
  copyright:
    startyear: 2016
  css_lazy_load: true
  cache_busting: true
  mainSections:
    - posts
    - updates
    - books
    - about
    - search
  tagline: "The directory of my thoughts"

  favicons: true
  feedSections:
    - posts
    - updates

  source:
    url: "https://gitlab.com/yashhere/yashhere.gitlab.io"
    md_dir: content
#  indieweb:
#    domain: "https://yashagarwal.in/"
#    webring: "\U00003297\U0000fe0f\U0001f34b\U0001f468\U0000200d\U0001f468\U0000200d\U0001f467\U0000200d\U0001f467"
#    webmention:
#      endpoint: "https://webmention.io/"
#      account: "https://yashagarwal.in"

  social:
    - name: Github
      link: "https://github.com/yashhere/"
      relme: true
    - name: Gitlab
      link: "https://gitlab.com/users/yashhere/projects"
      relme: true
    - name: Twitter
      link: "https://twitter.com/yash__here/"
      relme: true
    - name: Keybase.io
      link: "https://keybase.io/yash2696"
      icon: keybase
      relme: true

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
