[build]
  publish = "public"
  # functions = "functions"

[build.environment]
  NODE_VERSION = "16.13.1"
  NPM_VERSION = "8.1.2"
  YARN_VERSION = "1.22.17"

[context.production]
  command = "yarn run build"

[context.deploy-preview]
  command = "yarn run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "yarn run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "yarn run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	debug = true

[[plugins]]
  package = "netlify-plugin-subfont"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  # [plugins.inputs.thresholds]
  #   performance = 0.9
  #   accessibility = 0.9
  #   best-practices = 0.9
  #   seo = 0.9
  #   pwa = 0.9

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-debug-cache"

[dev]
  framework = "#custom"
  command = "yarn run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
