[build]
  publish = "public"
  # functions = "functions"

[build.environment]
  NODE_VERSION = "16.13.1"
  NPM_VERSION = "8.1.2"
  YARN_VERSION = "1.22.17"

[context.production]
  command = "yarn run build"

[context.deploy-preview]
  command = "yarn run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "yarn run build -- -b $DEPLOY_PRIME_URL"

[context.next]
  command = "yarn run build"

[context.next.environment]
  HUGO_ENV = "next"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-debug-cache"

# ATTENTION: this needs to be the last plugin
[[plugins]]
  package = "netlify-plugin-hashfiles"

[dev]
  framework = "#custom"
  command = "yarn run start"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
